[package]
name = "Proyecto3GC"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.18.0"
minifb = "0.26.0"
image = "0.23"

[profile.release]
opt-level = 2  # Reduce el nivel de optimización

